# Generated by Django 4.0.4 on 2022-04-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_description_alter_training_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Add an image'),
        ),
    ]
